//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timer.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timer.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Span xmlns=&apos;http://schemas.microsoft.com/winfx/2006/xaml/presentation&apos; xml:space=&apos;preserve&apos;&gt;
        ///    
        ///Timer is a small application used to quickly log time against Teamwork (https://www.teamwork.com) tasks and projects.
        ///&lt;LineBreak/&gt;
        ///The full source code is available on GitHub at https://github.com/roguelj/Timer.
        ///&lt;LineBreak/&gt;
        ///Check out the GitHub page for configuration details and documentation.
        ///&lt;LineBreak/&gt;
        ///
        ///&lt;/Span&gt;.
        /// </summary>
        public static string AboutDialogText {
            get {
                return ResourceManager.GetString("AboutDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string AnHourAgoButtonText {
            get {
                return ResourceManager.GetString("AnHourAgoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Task.
        /// </summary>
        public static string ClearSelectedTaskButtonText {
            get {
                return ResourceManager.GetString("ClearSelectedTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabelText {
            get {
                return ResourceManager.GetString("DescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DurationLabelText {
            get {
                return ResourceManager.GetString("DurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string EndLabelText {
            get {
                return ResourceManager.GetString("EndLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Billable.
        /// </summary>
        public static string IsBillableLabelText {
            get {
                return ResourceManager.GetString("IsBillableLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load all projects, tasks and tags..
        /// </summary>
        public static string LoadAllButtonText {
            get {
                return ResourceManager.GetString("LoadAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add my tasks for selected project..
        /// </summary>
        public static string LoadMyTasksForSelectedProjectButtonText {
            get {
                return ResourceManager.GetString("LoadMyTasksForSelectedProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load starred projects only (plus recent tasks and tags)..
        /// </summary>
        public static string LoadStarredButtonText {
            get {
                return ResourceManager.GetString("LoadStarredButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load all tasks for selected project..
        /// </summary>
        public static string LoadTasksForSelectedProjectButtonText {
            get {
                return ResourceManager.GetString("LoadTasksForSelectedProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LogButtonAboutDialog {
            get {
                return ResourceManager.GetString("LogButtonAboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LogButtonContextMenuUserDataPath {
            get {
                return ResourceManager.GetString("LogButtonContextMenuUserDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG TIME.
        /// </summary>
        public static string LogButtonText {
            get {
                return ResourceManager.GetString("LogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string NowButtonText {
            get {
                return ResourceManager.GetString("NowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Billable Time.
        /// </summary>
        public static string OkBillableButtonText {
            get {
                return ResourceManager.GetString("OkBillableButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Non-Billable Time.
        /// </summary>
        public static string OkNonBillableButtonText {
            get {
                return ResourceManager.GetString("OkNonBillableButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectLabelText {
            get {
                return ResourceManager.GetString("ProjectLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartLabelText {
            get {
                return ResourceManager.GetString("StartLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of Day.
        /// </summary>
        public static string StartOfDayButtonText {
            get {
                return ResourceManager.GetString("StartOfDayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagLabelText {
            get {
                return ResourceManager.GetString("TagLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskLabelText {
            get {
                return ResourceManager.GetString("TaskLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes ago.
        /// </summary>
        public static string TenMinutesAgoButtonText {
            get {
                return ResourceManager.GetString("TenMinutesAgoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes from now.
        /// </summary>
        public static string TenMinutesFromNowButtonText {
            get {
                return ResourceManager.GetString("TenMinutesFromNowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes ago.
        /// </summary>
        public static string ThirtyMinutesAgoButtonText {
            get {
                return ResourceManager.GetString("ThirtyMinutesAgoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes from now.
        /// </summary>
        public static string ThirtyMinutesFromNowButtonText {
            get {
                return ResourceManager.GetString("ThirtyMinutesFromNowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Log Detail.
        /// </summary>
        public static string TimeLogDetailDialogTitle {
            get {
                return ResourceManager.GetString("TimeLogDetailDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 minutes ago.
        /// </summary>
        public static string TwentyMinutesAgoButtonText {
            get {
                return ResourceManager.GetString("TwentyMinutesAgoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 minutes from now.
        /// </summary>
        public static string TwentyMinutesFromNowButtonText {
            get {
                return ResourceManager.GetString("TwentyMinutesFromNowButtonText", resourceCulture);
            }
        }
    }
}
